name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm --version
      - name: Add pnpm to PATH
        run: echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test